name: Crossterm (Windows)

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Tests (tui & crossterm)
        run: cargo test --no-fail-fast --no-default-features --features derive,serialize,tui,crossterm
        env:
          RUST_BACKTRACE: full
      - name: Tests (ratatui & crossterm)
        run: cargo test --no-fail-fast --no-default-features --features derive,serialize,ratatui,crossterm
        env:
          RUST_BACKTRACE: full
      - name: Examples
        run: cargo build --all-targets --examples
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --lib --no-default-features --features derive,serialize,tui,crossterm -- -Dwarnings
      - name: Clippy
        run: cargo clippy --lib --no-default-features --features derive,serialize,ratatui,crossterm -- -Dwarnings
