name: Tui-Crossterm

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Tests
        run: cargo test --no-fail-fast --features derive,serialize,tui,crossterm --no-default-features
        env:
          RUST_BACKTRACE: full
      - name: Examples
        run: cargo build --all-targets --examples
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --lib --features derive,serialize,tui,crossterm --no-default-features -- -Dwarnings
